#!/usr/bin/env bash

branch=$1
issue=$2
attach=${issue}
tmpdir="$(mktemp -d)"
curdir=$(pwd)
editor=${EDITOR:-nano}
range=$(git merge-base --fork-point master "${branch}").."${branch}"
curbranch=$(git rev-parse --abbrev-ref HEAD)
sit=$(which sit)

run() {
  if [ -z "${branch}" ]; then
    echo "Usage: prepare-merge-request <branch> [<issue>]"
    exit 1
  fi

  if [ -z "${sit}" ]; then
    echo "sit not found"
    exit 1
  fi

  git format-patch "${range}"  -o "${tmpdir}/git" || exit 2
  git log --reverse --pretty=format:"%s%n%n%b" "${range}" > "${tmpdir}/log" || exit 2
  $editor "${tmpdir}/log" || exit 2

  if [ -z "${attach}" ]; then
          issue=$(${sit} issue)
          issue_branch=${issue}
  else
          last_record=$(${sit} records ${issue} | tail -1)
          issue_branch="${issue}-${last_record}-$(date +%s)"
  fi

  git checkout -b "${issue_branch}" master || exit 2

  pushd "$(pwd)" >/dev/null || exit 2
  cd "${tmpdir}" || exit 2

  if [ -z "${attach}" ]; then
          tail -n +3 log > details
          head -n 1 log > text
          rm log

          "${sit}" -d "${curdir}" record -t SummaryChanged "${issue}" text || exit 2

          mv -f details text
          "${sit}" -d "${curdir}" record -t DetailsChanged,MergeRequested "${issue}" text git/*.patch || exit 2
  else
          mv log text
          "${sit}" -d "${curdir}" record -t Commented,MergeRequested "${issue}" text git/*.patch || exit 2
  fi

  popd >/dev/null || exit 2

  rm -rf "${tmpdir}"

  git add .sit/issues/"${issue}" || exit 2
  git commit -m "Added merge request: ${issue}" || exit 2
  git checkout "${curbranch}" || exit 2

  echo You can push the merge request:
  echo
  echo git push git@git.sit-it.org:sit-it/sit-inbox.git "${issue_branch}"
}

run
